name: Run API Tests and Upload to Allure TestOps

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Config Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run all tests
        run: mvn test

      - name: Upload Allure reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Download allurectl
        run: |
            curl -o allurectl https://repo.maven.apache.org/maven2/io/qameta/allurectl/0.24.2/allurectl_0.24.2_linux_amd64
            chmod +x allurectl
          
            sudo mv allurectl /usr/local/bin/allurectl

      - name: upload Allure TestOps
        env:
             ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
        run: |
          ./allurectl upload \
          --endpoint=https://api.testops.cloud \
          --project-id=1 \
          --results=target/allure-results \
          --launch-name="executed API GitHub" \
          --token $ALLURE_TOKEN