name: Run API Tests and Upload to Allure TestOps

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Config Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run all tests
        run: mvn test

      - name: Upload Allure reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Check allurectl file
        run: |
          file allurectl

      - name: Upload results to Allure TestOps
        if: always()
        env:
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
        run: |
          curl -slo allurectl https://github.com/allure-framework/allurectl/releases/latest/download/allurectl-linux
          
          chmod +x allurectl
          
          sudo mv allurectl /usr/local/bin/
      
          ./allurectl upload \
          --endpoint=https://api.testops.cloud \
          --project-id=1 \
          --results=target/allure-results \
          --launch-name="executed API GitHub" \
          --token $ALLURE_TOKEN